services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MrcMorales\MetaPixelApiBundle\Service\:
    resource: '../../Service'

  MrcMorales\MetaPixelApiBundle\MessageHandler\:
    resource: '../../MessageHandler'